### ISSUE TITLE
Possible UX problem in tablet

### ISSUE THREAD

**Issue by dpordomingo** [src-d/talks#9] opened 2017-02-22 17:22 UTC
**Description:**
In touch screens, it might be needed two click to close the speaker description.
Please, ensure that the described bug is not reproduced in native iPad navigators, nor other touch screens

**url:**
http://talks.sourced.tech/speakers

**env affected:**
touch screens

**reproduced with:**
chrome inspector, "responsive" feature using "iPad" mode

**steps to reproduce the bug:**
1. goto url
2. click in a speaker -> lightbox will be opened
3. try closing the lightbox clicking the "x" button
 ERR -> the lightbox will not be closed; the speaker name+socials will be closed
4. try closing the lightbox again clicking the "x" button
 -> the lightbox will be closed now

**Comment by erizocosmico** [comment] 2017-02-22 20:07
Can't reproduce on my iPad
On Wed, 22 Feb 2017 at 18:24, dpordomingo <notifications@github.com<mailto:notifications@github.com>> wrote:

Description:
In touch screens, it might be needed two click to close the speaker description.
Please, ensure that the described bug is not reproduced in native iPad navigators, nor other touch screens

url:
http://talks.sourced.tech/speakers

env affected:
touch screens

reproduced with:
chrome inspector, "responsive" feature using "iPad" mode

steps to reproduce the bug:

  1.  goto url
  2.  click in a speaker -> lightbox will be opened
  3.  try closing the lightbox clicking the "x" button
ERR -> the lightbox will not be closed; the speaker name+socials will be closed
  4.  try closing the lightbox again clicking the "x" button
-> the lightbox will be closed now

**Comment by dpordomingo** [comment] 2017-02-22 20:46
@erizocosmico Did you tried with Chrome?

If it only happens in Desktop Chrome Inspector, it is not a bug :)

**Comment by erizocosmico** [comment] 2017-02-22 20:48
Yep. Thought it happened but in the end I just missed the X button when I was clicking
On Wed, 22 Feb 2017 at 21:47, dpordomingo <notifications@github.com<mailto:notifications@github.com>> wrote:

@erizocosmico<https://github.com/erizocosmico> Did you tried with Chrome?

If it only happens in Desktop Chrome Inspector, it is not a bug :)

**Comment by Serabe** [comment] 2017-04-27 10:51
Closing since it cannot be reproduced

**Closed as completed by Serabe** 2017-04-27 10:51 UTC
